### PR TITLE
[BACKLOG-4063] - Included documentation for PromptPanel methods

### PR DESCRIPTION
**Pull request by diogofscmariano**
[BACKLOG-4138] - Reviewed PromptPanel module making not used methods private. Small refactor to WidgetBuilder usage and components construction cycle

### CODE REVIEW

**Comment by diogofscmariano** [comment]
@krivera-pentaho @plagoa @pamval @rfellows @scottyaslan @annapopova1 please review

**Comment by annapopova1** [comment]
functions: _mapComponents and _mapComponentsList were deleted by Kris. But you inserted it. Is it correct?

**Comment by diogofscmariano** [comment]
pr updated. please re-check

**Comment by diogofscmariano** [comment]
I removed methods that Kris had previously removed. Although, i'm going to review that, because doenst make sense to create CompositeComponent to do the iteration over components

**Comment by annapopova1** [comment]
good for me

**Comment by krivera-pentaho** [comment]
I agree. We shouldnot have to create the CompositeComponent simply to perform pre-order iteration.

**Pull request merged**
