### PR TITLE
[ANALYZER-2893] - Long measure names are not rendered correctly on Analyzer Layout pane

### PR DESCRIPTION
**Pull request by akhayrutdinov**
- crop long names

@rfellows, @bennychow, @krivera-pentaho, review it please

### CODE REVIEW

**Comment by krivera-pentaho** [comment]
Did we also want to truncate the end and add a "..." or just hide the overflow?

**Comment by akhayrutdinov** [comment]
@krivera-pentaho, that's a good question!
Actually, I decided to keep the behaviour of `gem-label` the same, as pivot's table header has (it does not suffer from the problem descibed in the ticket). The header has `text-overflow: clip` (default), meaning it is simply cutting the extra text. Also, we have left panel with controls and long text is also simply truncated there.

**Comment by lucboudreau** [comment]
Please make sure someone from UX pitches in on this one.

**Comment by akhayrutdinov** [comment]
OK, I've sent a letter to Wes (you are CCed). Let's wait for the UX feedback

**Comment by akhayrutdinov** [comment]
@krivera-pentaho, I've updated the PR according to UX team's recommendations. Review it please. There'll be another PR for Analyzer

**Pull request merged**
