### PR TITLE
[BISERVER-13277] PostProcessing Error Validation Message keeps showing on ReportViewer after validation is complete

### PR DESCRIPTION
**Pull request by mr9d**
- Parameters errors refreshment is fixed.

### CODE REVIEW

**Comment by mr9d** [comment]
@CodeOnCoffee @rfellows @mdamour1976 please review.

**Comment by mr9d** [comment]
@CodeOnCoffee @rfellows @mdamour1976 Wasn't able to reproduce unit tests failures locally, so I've had a discussion with @mchen-len-son about this failures and we decided it might be environment-specific.

**Comment by pamval** [comment]
@diogofscmariano @annapopova1 @krivera-pentaho please review

**Comment by krivera-pentaho** [comment]
Looks good to me

**Comment by mr9d** [comment]
@CodeOnCoffee @rfellows @mdamour1976 could you merge please?

**Pull request merged**
