### PR TITLE
[SP-2652] Backport of BISERVER-12918 - the report parameter/prompt panel flashes when auto submit off (6.1 Suite)

### PR DESCRIPTION
**Pull request by MikhailHubanau**
Draft PR.
Need to check js unit test before merge.

### CODE REVIEW

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by lucboudreau** [comment]
Please make sure to squash these commits before merging. Thanks.

**Comment by MikhailHubanau** [comment]
Squashed PR https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/765

**Pull request closed without merging**
