### PR TITLE
[ANALYZER-3313] - Drag and drop don't work in a Measure or Calculated…

### PR DESCRIPTION
**Pull request by apratkin**
… Measure with name '

### CODE REVIEW

**Comment by apratkin** [comment]
I run tasks:
ant clean-js resolve-js build-js test-js
ant -Dpentaho.resolve.repo=http://ivy-nexus.pentaho.org/content/groups/approved -Dtestreports.dir=bin/reports/unit-test -f build.xml clean-all resolve resolve-js jacoco && ant -Dpentaho.resolve.repo=http://ivy-nexus.pentaho.org/content/groups/approved -Dtestreports.dir=bin/reports/integration-test -f build.xml resolve resolve-js dist jacoco-integration test-js checkstyle

Both tasks completed successfully.

At wingman we have following error:
test-js:
Wed Aug 10 15:11:59 EDT 2016 - stdout - head: 
Wed Aug 10 15:11:59 EDT 2016 - stdout - head: BUILD FAILED
Wed Aug 10 15:11:59 EDT 2016 - stdout - head: /home/buildguy/project/build-res/subfloor-js.xml:430: Execute failed: java.io.IOException: Cannot run program "node_modules/karma/bin/karma" (in directory "/home/buildguy/project"): error=2, No such file or directory

**Comment by apratkin** [comment]
@rmansoor

**Comment by apratkin** [comment]
@rmansoor Could you, please, take a look and review my commit?

**Comment by mchen-len-son** [comment]
@rmansoor @bennychow @rfellows could you please take a look?

**Comment by mbatchelor** [comment]
Re-running wingman.

**Comment by mchen-len-son** [comment]
@rmansoor @bennychow @rfellows @mbatchelor can you please take a look?
the coverage drop doesn't seem to be related to the changes.

**Comment by rfellows** [comment]
not sure how java unit test coverage goes down when you only changed javascript files. that is strange.

**Pull request merged**
