### PR TITLE
[PIR-1291] A calendar isnt displayed in Filter pop-up window in PIR r…

### PR DESCRIPTION
**Pull request by mchen-len-son**
…eports
- increased z-index for dijit popups

### CODE REVIEW

**Comment by mchen-len-son** [comment]
Dijit popups are overlapped by pentaho.common.Dialog after #693.

@annapopova1 @tmorgner @rfellows @pamval please review

**Comment by lucboudreau** [comment]
Please see if you can fix these tests while you're working on this project. Thanks!

**Comment by mchen-len-son** [comment]
After a quick look, I don't see what exactly can cause these test failures.
They don't fail locally.

All I can think of, considering the failures I see, is that the HSQLDB is still initializing at the moment of these tests run.

> `assertTrue( "wrong column name", json.indexOf( "BC_PRODUCTS_PRODUCTLINE" ) != -1 );`
> `assertTrue( "wrong column type", json.indexOf( "\"string\"" ) != -1 );`
> `assertTrue( "wrong value: " + json, json.indexOf( "Classic Cars" ) != -1 );`

See? The first two checks passed, but the last one failed. Looks like the data was incomplete at that moment.

But, still, this is only a guess.

**Comment by pamval** [comment]
is there any other way to fix this issue? Using !important should be avoided at all costs, since there's no way to override or customize this style.

**Comment by mchen-len-son** [comment]
It's not working without !important.

I'll take a look for another ways.

**Comment by pentaho-lmartins** [comment]
Closing PR since JIRA issue is closed.

**Pull request closed without merging**
