### PR TITLE
[BACKLOG-6284] Base.js - Unit testing and dev API reference documentation

### PR DESCRIPTION
**Pull request by nantunes**
For review. @pentaho/millenniumfalcon

### CODE REVIEW

**Comment by nantunes** [comment]
For reference, initial review of @dcleao on a rewritten commit: https://github.com/nantunes/pentaho-platform-plugin-common-ui/commit/d326e1343ce75142cff66a7c8e2fc61b4defde48

**Comment by nantunes** [comment]
Coverage info:
> Statements: 100% (173 / 173)
> Branches: 93.07% (94 / 101)
> Functions: 93.55% (29 / 31)
> Lines: 100% (162 / 162)

**Comment by nantunes** [comment]
@dcleao Changes according to your comments.

Didn't create a jsdoc-only IBase interface, don't think it solves our problems. Any comment?

**Comment by nantunes** [comment]
Unexplored cases:
- [ ] Override a property with a getter and/or setter (either don't permit or resolve how to provide an useful this.base.

**Comment by dcleao** [comment]
@nantunes Hadn't seen the clone array bullet you added above...

In what an `IBase` interface is concerned, for moments, I thought you could be right, cause almost all of the Base interface is static.

But then, for my dismay, I found out that you can declare both **static** and **instance** members in an **interface** (by the way, @diogofscmariano, check out this case on static being legal/possible on arrays besides classes...):

idisposableinterfacewithstaticmembers

It's as easy as making something a _member_ of the interface directly, instead of of its "prototype":
```js
/**
 * @name disposeStatic
 * @memberOf pentaho.lang.IDisposable
 */
```

Interestingly, _TypeScript_ does have the concept of interfaces for the instance and for the static side of classes (checkout "Difference between static/instance side of class" a bit below [here](http://www.typescriptlang.org/Handbook#interfaces)).

One of the problems with the approach you took is that you're documenting `Base.Object` as being a subclass of `Base`, when, actually, `Base === Base.Object`. `Base.Object` is instead a subclass of the native `Object`.
Similarly, `Base.Array` is not a subclass of `Base`, but of the native `Array`.
(this description ignores the boot class which is created for each root, and actually creates a middle-man in the prototype chain; but this is a private implementation detail :-) )

**Comment by nantunes** [comment]
@dcleao and @graimundo please review.

**Comment by nantunes** [comment]
Review commit https://github.com/nantunes/pentaho-platform-plugin-common-ui/commit/43101a742dd73a9eedf7fd1fb9e874fae9aba7b8 for changes since last review.

**Comment by graimundo** [comment]
Great Work!

**Pull request merged**
