### PR TITLE
[BACKLOG-6898] - Re-implement PromptPanel#getString function

### PR DESCRIPTION
**Pull request by plagoa**
- Removed the getString function from the PromptPanel
- Required the localization service on the SubmitComponentBuilder
- Added message properties files with prompting specific messages
- Removed the unit tests from the prompt panel

### CODE REVIEW

**Comment by diogofscmariano** [comment]
Fine by me... the other prs? for RV and IR?

**Comment by diogofscmariano** [comment]
I would really love to have this tested. Can you encapsulate the messages.get in the builder and test?
we just need to make sure the localization service is called, not the localization service itself

**Comment by diogofscmariano** [comment]
@pentaho/orlandocalisbon ^^

**Comment by plagoa** [comment]
@diogofscmariano sure will do that in a bit then.

**Comment by plagoa** [comment]
@diogofscmariano updated PR with the test for this. please review.

**Comment by diogofscmariano** [comment]
Perfect. Merging this along with other two

**Comment by plagoa** [comment]
@diogofscmariano made that change and updated the test.

**Comment by diogofscmariano** [comment]
along https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/673/files and https://github.com/pentaho/pentaho-platform-plugin-interactive-reporting/pull/330

**Pull request merged**
