### PR TITLE
[ANALYZER-2933] Fixes tooltip not showing "measure interpolated" suffix for interpolated measures.

### PR DESCRIPTION
**Pull request by SergeyTravin**
@e-cuellar, @mdamour1976  could you merge it?

### CODE REVIEW

**Comment by mdamour1976** [comment]
@SergeyTravin  Since this code is in common-ui, the affected areas may be greater than just Analyzer, has it been considered to protected against regressions introduced by possible NPE:
                    var complexInterp = context.scene.datums()
I see the assumption here may be fine if we always have context.scene.datums, but a tiny bit of protection will make me feel slightly more comfortable (especially not knowing this code).

**Comment by SergeyTravin** [comment]
@mdamour1976, Great thanks for important notes. I changed the code. Could you review it again?

**Comment by mdamour1976** [comment]
I was thinking more about each part of this, rather than the whole..
context.scene.datums()

Not that it is possible (I don't know), but if context is null, we can still NPE on context.scene.

And same for context.scene.datums() if context.scene is null.

So we should add some:

if ( context && context.scene ) {
  // do the right thing
}

**Comment by SergeyTravin** [comment]
@mdamour1976, I don't believe that it is possible, but I changed code to avoid this situation at future.

**Comment by dcleao** [comment]
Yep, I can confirm that there is no possibility for a NPE to occur. Of course, if something goes really bad, somewhere upstack, who knows.

**Comment by SergeyTravin** [comment]
@mdamour1976, any comments?

**Comment by SergeyTravin** [comment]
@nbaker, @rfellows, @mdamour1976 Could you provide any feedback?

**Comment by SergeyTravin** [comment]
@dkincade,  @nbaker, @rfellows, @mdamour1976 Could you provide any feedback?

**Comment by dcleao** [comment]
@mdamour1976, @SergeyTravin: upon refactor of code in future develop branch I passed through this commit's code and spotted an error. Sergey's change to avoid NPE introduced a ReferenceError...

The original code was (from https://github.com/dcleao/pentaho-platform-plugin-common-ui/commit/668b473b1e15b6b9eef87538a545b8fb10d93bf7):

```javascript
var complexInterp = context.scene.datums()
    .where (function(d) { return d.isInterpolated && d.interpDimName === cccDimName; })
    .first();
    if(complexInterp) {
        suffix = this.chart._message('chartTooltipGemInterp_' + complexInterp.interpolation);
```

In the new code, variable `complexInterp` is not defined...

To protect against NPE, you can instead do:
```javascript
var complexInterp = context && context.scene && context.scene.datums()
    .where (function(d) { return d.isInterpolated && d.interpDimName === cccDimName; })
    .first();
    if(complexInterp) {
        suffix = this.chart._message('chartTooltipGemInterp_' + complexInterp.interpolation);
```

This issue is planned for 5.4...

**Pull request merged**
