### PR TITLE
[FIX][BACKLOG-6625] Normalize resourceIDs in i18nMock plugin

### PR DESCRIPTION
**Pull request by nantunes**
@dcleao please review.

### CODE REVIEW

**Comment by dcleao** [comment]
I know we don't have strict formatting rules, but it's a good rule to preserve the active rules in a file, not to leave it in no man's land :-(
Otherwise, great!

**Comment by nantunes** [comment]
Ok. _"Don't mess with the original"_ style rule seems ok to me. 😉

**Comment by dcleao** [comment]
I know I sometimes failed to comply with this rule in the past... But, anyway, I try :-)

**Comment by dcleao** [comment]
Great!

**Pull request merged**
