### PR TITLE
[BACKLOG-2540] - Convert Viz API to AMD

### PR DESCRIPTION
**Pull request by dcleao**
Should be accepted along with companion pentaho/pentaho-analyzer#563.

@pminutillo, @bennychow  please review.

### CODE REVIEW

**Comment by dcleao** [comment]
@DFieldFL please review

**Comment by DFieldFL** [comment]
looks good to me.

**Comment by dcleao** [comment]
@pminutillo please don't forget this one.
@bennychow already accepted the Analyzer pull-request, and it depends on this one!

**Comment by pminutillo** [comment]
@dcleao looks good to me too

**Comment by dcleao** [comment]
@bennychow the ball is yours.

**Comment by dcleao** [comment]
@pminutillo, @DFieldFL: I added a few commits after your review. Feel free to review those, and if needed, I can make a subsequent PR.
Thanks!

**Pull request merged**
