### PR TITLE
[SP-1771] Backport of PRD-5398 - Prompt screen flashes and take user back to the top again

### PR DESCRIPTION
**Pull request by MikhailHubanau**
@dcleao @rfellows 
Please review.

### CODE REVIEW

**Comment by MikhailHubanau** [comment]
@dcleao @rfellows 
Please review.

**Comment by dcleao** [comment]
Please see my comments in https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/366

**Comment by MikhailHubanau** [comment]
@dcleao @rfellows 
Please review.

**Comment by dcleao** [comment]
Looks perfect to me. @rfellows, I leave the ball to you :-)

**Pull request merged**
