### PR TITLE
[BACKLOG-36160] Declare the stock CCC/View class hierarchy to the JS Modules API

### PR DESCRIPTION
**Pull request by dcleao**
PR set: https://github.com/pentaho/pentaho-analyzer/pull/2287

(Follows https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1581 which was inadvertently closed due to deleting of the target branch)

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 27s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **73**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/common-ui-11/job/PR-1583/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by dcleao** [comment]
@himanshu6201, @varuntangirala, @NJtwentyone, @rmansoor please review.

**Comment by dcleao** [comment]
@pentaho/hoth please review.

**Review by soagarwal1 — APPROVED** [review]

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 31s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **73**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/common-ui-11/job/PR-1583/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 20s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **73**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/common-ui-11/job/PR-1583/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by rmansoor — APPROVED** [review]

**Pull request merged**
