### PR TITLE
[BACKLOG-6052] More refactoring to Context.Spec + support type construction with temporary ids

### PR DESCRIPTION
**Pull request by dcleao**
* Tried to modularize the helper methods used to build test functions.
* Moved some resulting "primitives" to a new `test-utils.js` AMD module.
* Others, integrated into `require-test.js`

* Support for construction of types from generic type specifications with temporary ids.

@pentaho/millenniumfalcon please review.

### CODE REVIEW

**Comment by dcleao** [comment]
Please don't merge yet. Found a bug.

**Comment by dcleao** [comment]
Guys, I ended up joining the temporary id changes (the whole reason for the new Context.Spec.js refactoring).

**Comment by nantunes** [comment]
Seems :ok: to me.

**Comment by nantunes** [comment]
@pentaho/millenniumfalcon anything preventing merge?

**Pull request merged**
