### PR TITLE
[BACKLOG-6292] text spec and doc

### PR DESCRIPTION
**Pull request by scottyaslan**

### CODE REVIEW

**Comment by scottyaslan** [comment]
@pentaho/millenniumfalcon

**Comment by carlosrusso** [comment]
What about sanity tests (e.g. feeding nulls) ?

**Comment by graimundo** [comment]
@scottyaslan please rebase with the fixed test-js location. See https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/618 for more information.

**Comment by scottyaslan** [comment]
@graimundo rebased to reflect new test-js location

**Comment by scottyaslan** [comment]
YAY!....lol….do you ever sleep?

**Pull request merged**
