### PR TITLE
[BACKLOG-9052] Configure the Axis defaults for DET charts

### PR DESCRIPTION
**Pull request by dcleao**
@pentaho/millenniumfalcon please review.

### CODE REVIEW

**Comment by nantunes** [comment]
@dcleao It is ok. Don't you what to rebase 4025edd on master so it can be merged earlier?

**Comment by dcleao** [comment]
@nantunes I could, but this commit depends on the "extension" feature implemented in the code of the previous PR, and although rebasing may cause no problems, the code itself wouldn't work if merged earlier.

**Comment by nantunes** [comment]
@dcleao #791 is merged, so you can now rebase on master to fix this PR (the squash commit changes the git tree).

**Comment by dcleao** [comment]
@pentaho/millenniumfalcon rebased.

**Pull request merged**
