### PR TITLE
[CLEANUP] Moving jsdoc files to a separate content root (like that of tests)

### PR DESCRIPTION
**Pull request by dcleao**
Plus:
* Fixed missing public stylesheet of generated jsdoc output
* Updated jsdoc version

@pentaho/millenniumfalcon please review.

### CODE REVIEW

**Comment by dcleao** [comment]
@diogofscmariano please review.

**Comment by diogofscmariano** [comment]
Good change. Why dont we just have its folder as doc-js? Shouldnt all our doc be jsdoc? :)

**Comment by dcleao** [comment]
@diogofscmariano Unfortunately, the "doc-js" folder is already taken by ant/subfloor to be the output folder of generated documentation! Changing this would require changing subfloor-js...
But that was my wish, and we probably can do it like that, if appropriate, in maven projects.

**Comment by diogofscmariano** [comment]
Too much time working in maven things... you are right :(

**Pull request merged**
