### PR TITLE
[BACKLOG-6253] complex.js unit tests

### PR DESCRIPTION
**Pull request by nantunes**

### CODE REVIEW

**Comment by nantunes** [comment]
@pentaho/millenniumfalcon please review.

**Comment by nantunes** [comment]
@dcleao @graimundo

**Comment by nantunes** [comment]
Fixed. @dcleao

**Comment by dcleao** [comment]
Great for me. @graimund be my guest :-)

**Comment by dcleao** [comment]
@graimundo

**Pull request merged**
