### PR TITLE
[BACKLOG-4070] -- added the index where to insert components for the …

### PR DESCRIPTION
**Pull request by krivera-pentaho**
…cdf dashboard

### CODE REVIEW

**Comment by krivera-pentaho** [comment]
@pamval @diogofscmariano @annapopova1 @plagoa @rfellows @scottyaslan please review

**Comment by diogofscmariano** [comment]
@krivera-pentaho we should have unit tests for this

**Comment by krivera-pentaho** [comment]
I will update the unit tests

**Comment by annapopova1** [comment]
General all good for me, but probably need squash commits.

**Comment by krivera-pentaho** [comment]
Sure, i will squash them

**Comment by krivera-pentaho** [comment]
Squashed

**Pull request merged**
