### PR TITLE
[BACKLOG-5837] - Prompt API - Implement setParameterValue

### PR DESCRIPTION
**Pull request by plagoa**
- added the ability to getParameterName using a string as an input instead of an object

### CODE REVIEW

**Comment by plagoa** [comment]
@diogofscmariano @pamval @annapopova1 @krivera-pentaho please review

**Comment by krivera-pentaho** [comment]
Looks good to me

**Comment by plagoa** [comment]
Had to make a few fixes. 

@diogofscmariano @pamval @annapopova1 @krivera-pentaho please review

**Comment by annapopova1** [comment]
Probably need add unit test for PromptPanel#getParameterName because you changed implementation.

**Comment by plagoa** [comment]
@annapopova1 I added the unit test. please review

**Comment by annapopova1** [comment]
Looks good for me

**Comment by diogofscmariano** [comment]
@plagoa can we please make sure we have this documentation a bit extended? 
@plagoa also, please make sure Virginia reviews this documentation

**Comment by plagoa** [comment]
@diogofscmariano updated the documentation. Please review.

**Comment by diogofscmariano** [comment]
@annapopova1 can you please follow this up on the builds and check it?

**Comment by annapopova1** [comment]
@diogofscmariano It works but IMO comment for user is unclear.
Now it's "* api.operation.setParameterValue(param, value);" I think more understandable to write concrete parameter's name and value.
I will change it and add to my PR https://github.com/pentaho/pentaho-platform-ee/pull/863

**Pull request merged**
