### PR TITLE
[BACKLOG-5355] -- cleared nullValueParams variable to halt infinite loop

### PR DESCRIPTION
**Pull request by krivera-pentaho**

### CODE REVIEW

**Comment by krivera-pentaho** [comment]
@dkincade please review
already tested and merged into master. unit tests are passing.

**Comment by krivera-pentaho** [comment]
@pamval please review

**Comment by dkincade** [comment]
But were the unit tests passing before? (can we add a test to prevent this from regressing in the future)?

**Comment by krivera-pentaho** [comment]
Unfortunately not. This would have to be an integration test that we would have to add to verify that this problem won't happen again. It was spanning multiple "on" events which we would not be able to capture inside of a unit test.

**Pull request merged**
