### PR TITLE
[BISERVER-12918] - the report parameter/prompt panel flashes when auto submit off

### PR DESCRIPTION
**Pull request by akhayrutdinov**
@pamval, @diogofscmariano, @krivera-pentaho, review it please. This is a replacement of https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/546

@MikhailHubanau is absent until the middle of Jan, that is why I picked his changes and added tests as well as some small changes.

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@pamval, @diogofscmariano, @krivera-pentaho, review it please.

**Comment by akhayrutdinov** [comment]
@pamval, @diogofscmariano, @krivera-pentaho, review it please

**Comment by diogofscmariano** [comment]
@akhayrutdinov can you please squash? apart from this, everything looks great

**Comment by krivera-pentaho** [comment]
Looks ok to me. Will merge after commits are squashed.

**Comment by akhayrutdinov** [comment]
@diogofscmariano, @krivera-pentaho, I've done the squashing

**Pull request merged**
