### PR TITLE
[PPP-3510] - Use of vulnerable component - handlebars.js v1.0.0-rc.3

### PR DESCRIPTION
**Pull request by YuryBY**
@pentaho/millenniumfalcon, @carlosrusso, @rfellows, would you mind of reviewing/merging?

### CODE REVIEW

**Comment by dcleao** [comment]
@diogofscmariano I saw you commented on the issue. Can you review this?

**Comment by YuryBY** [comment]
@diogofscmariano, @pentaho/millenniumfalcon, @carlosrusso, @rfellows, any updates here?
Note: https://github.com/pentaho/pentaho-platform/pull/2947 should merge right after the current commit.

**Comment by pamval** [comment]
@diogofscmariano please review

**Comment by diogofscmariano** [comment]
fine by me, as long as there are no regressions from jumping major releases... 
probably we need to submit a component process for this new version

**Comment by pamval** [comment]
@YuryBY yes we need a new component ticket for the new version of handlebars.

**Comment by YuryBY** [comment]
@diogofscmariano, here is corresponding tickets:
http://jira.pentaho.com/browse/COMP-3189
http://jira.pentaho.com/browse/COMP-3190

**Pull request merged**
