### PR TITLE
[BACKLOG-6875] PIR: Review paramDefn usage

### PR DESCRIPTION
**Pull request by annapopova1**
@pentaho/orlandocalisbon please review

### CODE REVIEW

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by diogofscmariano** [comment]
@brosander can you please check this? 
This might be a case of another pr that needs to be manually checked?

**Comment by jvelasques** [comment]
I was able to locally build and run the tests (targets: test-js test integration-test)

**Pull request merged**
