### PR TITLE
[BACKLOG-14852] Creates a new File Install using the ManagedServiceFactory

### PR DESCRIPTION
**Pull request by nantunes**
@pentaho/millenniumfalcon and @pentaho-nbaker please review.

This is needed by https://github.com/pentaho/pentaho-karaf-assembly/pull/298 and https://github.com/pentaho/pentaho-karaf-ee-assembly/pull/110.

### CODE REVIEW

**Comment by nantunes** [comment]
The related-and-also-still-WIP karaf-assembly PR is https://github.com/pentaho/pentaho-karaf-assembly/pull/298.

**Comment by nantunes** [comment]
@pentaho-nbaker FYI.

**Comment by graimundo** [comment]
@CodeOnCoffee FYI

**Comment by pentaho-nbaker** [comment]
Perfect!

**Comment by pentaho-nbaker** [comment]
Guys We're right in the middle of the nightly build. I'll merge it later and it will be available for QAT testing Tuesday

**Comment by nantunes** [comment]
@pentaho-nbaker This is still WIP... We also need a feature. I'll update the PR soon.

**Comment by nantunes** [comment]
Updated, rebased and description changed.

**Pull request merged**
