### PR TITLE
[BACKLOG-6733] ConfigurationService: add and select config

### PR DESCRIPTION
**Pull request by nantunes**
Depends on #734.

@pentaho/millenniumfalcon please take a look.

### CODE REVIEW

**Comment by nantunes** [comment]
Rebased and updated with also the select functionality. Includes the merge code from @dcleao.

@pentaho/millenniumfalcon please review.

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by dcleao** [comment]
Great!

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by nantunes** [comment]
@dcleao JsDocs changes merged and commits squashed. Please merge to master.

**Comment by brosander** [comment]
Base build failed with return code 1

**Pull request merged**
