### PR TITLE
[SP-2887][BISERVER-13277] PostProcessing Error Validation Message kee…

### PR DESCRIPTION
**Pull request by mchen-len-son**
…ps showing on ReportViewer after validation is complete

- added update forcing when errors are changed at PromptPanel

### CODE REVIEW

**Comment by mchen-len-son** [comment]
This is a partial backport of #823.

**Comment by mchen-len-son** [comment]
@pamval @mbatchelor please review

**Comment by mchen-len-son** [comment]
@tmorgner @rfellows could you please take a look?
thanks.

**Comment by tmorgner** [comment]
Looks sane to me.

**Pull request merged**
