### PR TITLE
[BACKLOG-9339] - 'Error parsing parameter information' when inputting…

### PR DESCRIPTION
**Pull request by Aliaksandr-Kastenka**
… invalid data in the text box parameter

Additional check added in order to avoid exception at this point: paramSelectedValue.toUpperCase().

### CODE REVIEW

**Comment by Aliaksandr-Kastenka** [comment]
@pamval 
Please review.

**Comment by pamval** [comment]
@annapopova1 @afrjorge @krivera-pentaho please review this change

**Comment by annapopova1** [comment]
Looks like this error can be happened not only for "java.lang.String" type because as inputs we have paramValue as string and paramSelectedValue as empty array. And after that we try fn toUpperCase for array. Probably for some cases we can have not empty array and as a result potential issue. Another potential case when we have paramSelectedValue as empty string and probably wrong comparison. 
IMO '_areParamsDifferent' function should have smarter logic to compare different types.
In addition will be better to have unit tests to cover possible changes.

**Comment by Aliaksandr-Kastenka** [comment]
@annapopova1 
I checked other possible types of paramSelectedValue(Date and Number) and as far as I see everything works as expected. Added js-test to cover this change.

**Comment by Aliaksandr-Kastenka** [comment]
@pamval 
Please review.

**Comment by pamval** [comment]
@annapopova1 please review this pull request

**Comment by annapopova1** [comment]
Sorry for so late response.
Now code looks good. But I can't say anything about ParameterValidator because I have not had experience of working with it.

**Pull request merged**
