### PR TITLE
[BACKLOG-16958] Removes node_modules dir during clean

### PR DESCRIPTION
**Pull request by axelguiloff**
@pentaho/x-wing Please review

### CODE REVIEW

**Comment by tmcsantos** [comment]
Couldn't this be done in the parent poms?
I think there are more projects with the same issue.

**Comment by graimundo** [comment]
@tmcsantos I agree that this should be done in the parent poms. This is most likely affecting more projects other than common-ui. What's the profile that is being executed that installs node modules? Most likely the clean plugin should be put in that profile as well.

@diogofscmariano any inputs on this topic?

**Comment by tmcsantos** [comment]
I believe the profile active profile would be this one. https://github.com/pentaho/maven-parent-poms/blob/master/pom.xml#L520

**Comment by diogofscmariano** [comment]
@graimundo no, just the fact that if we are on a clean environment, deleting that will cause all the node/npm environment to be reinstalled. IMO, the right approach would be to put this inside the target folder, but we already had problems/discussions in the past with that

**Comment by graimundo** [comment]
@diogofscmariano I agree with you. Now that we have more experience and use cases of projects that are using node modules It's probably time to revisit the subject of where node modules should be put and when they should be cleaned. I would put this PR on hold until that discussion takes place Does @pentaho/x-wing agree?

**Comment by axelguiloff** [comment]
Closing this PR pending further discussion

**Pull request closed without merging**
