### PR TITLE
[WIP][BACKLOG-7551] Support multi-valued properties in the "change" event loop

### PR DESCRIPTION
**Pull request by carlosrusso**
This pull request is here for review purposes for @pentaho/millenniumfalcon, i.e. as a means for collecting feedback.

It implements a variant of #743, following the outlines discusses during early stages of review.
When either variant reaches maturity to be merged into master, the history will be dealt with appropriately. 

Therefore, please DO NOT MERGE yet.

### CODE REVIEW

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by dcleao** [comment]
👍

**Comment by carlosrusso** [comment]
Closing this pull request in favour of its squashed variant (#766)

**Pull request closed without merging**
