### PR TITLE
[BISERVER-12918] - Removed default case and handled it properly based…

### PR DESCRIPTION
**Pull request by diogofscmariano**
… on if the param is a list or not, basically the same if it is a textbox, just like it was before. Tests updated accordingly

@tmorgner @pamval please review

### CODE REVIEW

**Comment by brosander** [comment]
http://wingman.pentaho.com:8080/job/wingman/36/

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by diogofscmariano** [comment]
BUILD FAILED
Mon Apr 04 12:07:51 EDT 2016 - stdout - head: /home/buildguy/project/build-res/subfloor-pkg.xml:439: impossible to publish artifacts for pentaho#common-ui;7.0-SNAPSHOT: java.io.IOException: missing artifact pentaho#common-ui;7.0-SNAPSHOT!common-ui.zip was the result... 
Can it be fired again?

**Comment by diogofscmariano** [comment]
@brosander ^^

**Comment by brosander** [comment]
http://wingman.pentaho.com:8080/job/wingman/39/

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by diogofscmariano** [comment]
@brosander something is not working correctly out of my control... anything i have to do on my side to help moving this forward?

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman-ant-cmd/16/

**Comment by pamval** [comment]
@diogofscmariano review this one manually.

**Comment by brosander** [comment]
@diogofscmariano it's possible that publish-local borks this build, I can add an exception to the wingman config for it but I need to see if removing it helps, just kicked off a custom ant command build

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m jacoco-integration checkstyle

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  package-res/resources/web/prompting/WidgetBuilder.js
  test-js/unit/prompting/WidgetBuilderSpec.js

Still Broken Tests:
======================
org.pentaho.common.ui.metadata.service.MetadataService2IT.testJsonQueryToCdaJson1:
-----------------------------------------------
java.lang.UnsupportedOperationException
```
java.lang.UnsupportedOperationException
	at org.pentaho.commons.connection.AbstractPentahoMetaData.getAttribute(AbstractPentahoMetaData.java:130)
	at org.pentaho.common.ui.metadata.service.MetadataServiceUtil2.createCdaJson(MetadataServiceUtil2.java:258)
	at org.pentaho.common.ui.metadata.service.MetadataService2.doXmlQueryToCdaJson(MetadataService2.java:317)
	at org.pentaho.common.ui.metadata.service.MetadataService2.doJsonQueryToCdaJson(MetadataService2.java:361)
	at org.pentaho.common.ui.meta
```
org.pentaho.common.ui.metadata.service.MetadataService2IT.testXmlQueryToCdaJson1:
-----------------------------------------------
java.lang.UnsupportedOperationException
```
java.lang.UnsupportedOperationException
	at org.pentaho.commons.connection.AbstractPentahoMetaData.getAttribute(AbstractPentahoMetaData.java:130)
	at org.pentaho.common.ui.metadata.service.MetadataServiceUtil2.createCdaJson(MetadataServiceUtil2.java:258)
	at org.pentaho.common.ui.metadata.service.MetadataService2.doXmlQueryToCdaJson(MetadataService2.java:317)
	at org.pentaho.common.ui.metadata.service.MetadataService2IT.testXmlQueryToCdaJson1(MetadataService2IT.java:782)

```
org.pentaho.common.ui.metadata.service.MetadataServiceIT.testJsonQueryToCdaJson1:
-----------------------------------------------
java.lang.UnsupportedOperationException
```
java.lang.UnsupportedOperationException
	at org.pentaho.commons.connection.AbstractPentahoMetaData.getAttribute(AbstractPentahoMetaData.java:130)
	at org.pentaho.common.ui.metadata.service.MetadataServiceUtil2.createCdaJson(MetadataServiceUtil2.java:258)
	at org.pentaho.common.ui.metadata.service.MetadataService.doXmlQueryToCdaJson(MetadataService.java:310)
	at org.pentaho.common.ui.metadata.service.MetadataService.doJsonQueryToCdaJson(MetadataService.java:354)
	at org.pentaho.common.ui.metadata
```
org.pentaho.common.ui.metadata.service.MetadataServiceIT.testXmlQueryToCdaJson1:
-----------------------------------------------
java.lang.UnsupportedOperationException
```
java.lang.UnsupportedOperationException
	at org.pentaho.commons.connection.AbstractPentahoMetaData.getAttribute(AbstractPentahoMetaData.java:130)
	at org.pentaho.common.ui.metadata.service.MetadataServiceUtil2.createCdaJson(MetadataServiceUtil2.java:258)
	at org.pentaho.common.ui.metadata.service.MetadataService.doXmlQueryToCdaJson(MetadataService.java:310)
	at org.pentaho.common.ui.metadata.service.MetadataServiceIT.testXmlQueryToCdaJson1(MetadataServiceIT.java:809)

```

**Comment by brosander** [comment]
@diogofscmariano also doesn't look like we've configured this project for js tests, sec

**Comment by diogofscmariano** [comment]
@jvelasques didnt you fixed this java tests? ^^

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman-ant-cmd/17/

**Comment by jvelasques** [comment]
I fixed the java tests which broke on my java's installation - https://github.com/pentaho/pentaho-platform-plugin-common-ui/commit/495f7df1f2985e8eff9fb002e15405c3123d1714
Its possible there are other places making the same (or other) wrong order assumptions, but my machine just didn't fail on those.

**Comment by lucboudreau** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Mon Apr 04 12:38:14 EDT 2016 - stdout - base:      [exec] PhantomJS 2.1.1 (Linux 0.0.0) ERROR: 'There is no timestamp for /base/build-res/module-scripts/cdf/Logger.js!'
Mon Apr 04 12:38:14 EDT 2016 - stdout - base:      [exec] 
Mon Apr 04 12:38:14 EDT 2016 - stdout - base:      [exec] PhantomJS 2.1.1 (Linux 0.0.0) ERROR: 'There is no timestamp for /base/build-res/module-scripts/cdf/lib/Base.js!'
Mon Apr 04 12:38:14 EDT 2016 - stdout - base:      [exec] 
Mon Apr 04 12:38:14 EDT 2016 - stdout - base:      [exec] PhantomJS 2.1.1 (Linux 0.0.0) ERROR
Mon Apr 04 12:38:14 EDT 2016 - stdout - base:      [exec]   Error: Script error for "dojo/parser"
Mon Apr 04 12:38:14 EDT 2016 - stdout - base:      [exec]   http://requirejs.org/docs/errors.html#scripterror
Mon Apr 04 12:38:14 EDT 2016 - stdout - base:      [exec]   at /home/buildguy/project/node_modules/requirejs/require.js:140
Mon Apr 04 12:38:14 EDT 2016 - stdout - base:      [exec] 
Mon Apr 04 12:38:14 EDT 2016 - stdout - base:      [exec] 
Mon Apr 04 12:38:14 EDT 2016 - stdout - base:      [exec] [36m04 04 2016 16:38:13.978:DEBUG [karma]: [39mRun complete, exiting.
Mon Apr 04 12:38:14 EDT 2016 - stdout - base:      [exec] [36m04 04 2016 16:38:13.979:DEBUG [launcher]: [39mDisconnecting all browsers
Mon Apr 04 12:38:14 EDT 2016 - stdout - base:      [exec] PhantomJS 2.1.1 (Linux 0.0.0) ERROR
Mon Apr 04 12:38:14 EDT 2016 - stdout - base:      [exec]   Error: Script error for "dojo/ready"
Mon Apr 04 12:38:14 EDT 2016 - stdout - base:      [exec]   http://requirejs.org/docs/errors.html#scripterror
Mon Apr 04 12:38:14 EDT 2016 - stdout - base:      [exec]   at /home/buildguy/project/node_modules/requirejs/require.js:140
Mon Apr 04 12:38:14 EDT 2016 - stdout - base:      [exec] 
Mon Apr 04 12:38:14 EDT 2016 - stdout - base:      [exec]

**Comment by brosander** [comment]
is that a sign of misconfiguration? or a problem with the tests?

**Comment by diogofscmariano** [comment]
@brosander checking it manually again, give me a sec

**Comment by brosander** [comment]
@diogofscmariano it's in the base build (before pr applied) so if you fixed it with this then I'd vote for a manual review

**Comment by diogofscmariano** [comment]
@brosander there is an issue with the js test from the order they run... checking it. Java tests nothing here, give me a bit and i will update the pr

**Comment by diogofscmariano** [comment]
pr updated, @brosander please check

**Comment by brosander** [comment]
@diogofscmariano the base build was failing so wingman won't give meaningful output, manual review recommended

**Pull request merged**
