### PR TITLE
[BISERVER-13107] Query-driven textbox parameters defined as Number ar…

### PR DESCRIPTION
**Pull request by SergeyTravin**
…e formatted as ##,### when screen reloads

- remove default formating by dojo

### CODE REVIEW

**Comment by SergeyTravin** [comment]
@diogofscmariano, @krivera-pentaho, @rfellows According the e-mail from Thomas Morgner  we should not use format exclude than its define. If we do not have  formatter than we use v.label.   Could you please review it?

**Comment by SergeyTravin** [comment]
@diogofscmariano, @krivera-pentaho, @rfellows Could you please review it?

**Comment by krivera-pentaho** [comment]
This looks good to me.

**Comment by diogofscmariano** [comment]
are we aware that removing this code section will probably break http://jira.pentaho.com/browse/PIR-920?

**Comment by tmorgner** [comment]
No, I disagree. Our bug here was that we applied a formatter by "guessing" the format string. We applied a format to anything that looks remotely like a number, regardless of whether the parameter had a format-string defined. We now make that more strict and only format data if the user explicitly requested it.

It therefore should NOT break PIR-920, assuming that their prompt has an explicit format-string defined.

 If they have defined the parameter with a format-string, we will still apply the formatter, according to this line:

> initialValue = this.formatter ? this.formatter.format(this.transportFormatter.parse(v.label)) : v.label;

**Comment by diogofscmariano** [comment]
Thanks for the clarification Thomas

**Pull request merged**
